version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.14.0
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root-token"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    command: server -dev
    volumes:
      - vault_data:/vault/file
    networks:
      - localnet

  prometheus:
    image: prom/prometheus:v2.46.0
    container_name: prometheus
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - localnet

  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - localnet

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: telegram-quote-bot
    env_file:
      - .env
    depends_on:
      - vault
      - prometheus
    environment:
      PROMETHEUS_URL: "http://prometheus:9090"
      VAULT_ADDR:     "http://vault:8200"
      VAULT_TOKEN:    "root-token"
    ports:
      - "8001:8000"
    networks:
      - localnet
    restart: unless-stopped

volumes:
  vault_data:

networks:
  localnet:
    driver: bridge
