global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'telegram-quote-bot'
    metrics_path: /metrics
    static_configs:
      - targets: ['bot:8001']

